"""
app/services/frd_generator.py
Core FRD generation service.
Combines retrieved RAG context with input documents and calls the LLM
using the MASTER PROMPT to produce a structured Markdown FRD.
"""
from datetime import date
from typing import List

from app.services.llm_service import LLMService
from app.models.schemas import RetrievedFRD


# ─────────────────────────────────────────────────────────────────────────────
# MASTER PROMPT — The heart of the FRD generator
# ─────────────────────────────────────────────────────────────────────────────

SYSTEM_PROMPT = """You are a Senior Business Analyst and Solution Architect with 15+ years of enterprise experience.
Your task is to generate a COMPLETE, CLIENT-READY Functional Requirement Document (FRD).

STRICT RULES:
1. Generate ALL sections listed below — do NOT skip any.
2. Each Functional Requirement MUST include: ID, Title, Description, Actor, Priority (High/Medium/Low), and 2-3 Acceptance Criteria.
3. Mark any requirement not explicitly stated in the input as [INFERRED].
4. Do NOT hallucinate facts — if something is unclear, flag it as an Open Question.
5. Business Rules must be written as unambiguous decision rules (if/then preferred).
6. Use professional enterprise language throughout.
7. Output the FRD in clean Markdown format.

OUTPUT FORMAT — Generate the FRD with EXACTLY these sections in order:

# Functional Requirement Document
## {project_name}
**Version:** 1.0  |  **Date:** {date}  |  **Status:** Draft  |  **Prepared by:** FRD AI Agent

---

## 1. Business Objective
[2-4 sentence summary of what the project aims to achieve and why]

## 2. Scope
### 2.1 In Scope
- [bullet list]

### 2.2 Out of Scope
- [bullet list]

## 3. Stakeholders
| Name / Role | Type | Responsibility |
|---|---|---|
[table rows]

## 4. Assumptions
- [bullet list]

## 5. Dependencies
- [bullet list]

## 6. Functional Requirements
| ID | Title | Actor | Priority |
|---|---|---|---|
[summary table]

### Detailed Requirements
#### FR-01: [Title]
- **Description:** ...
- **Actor:** ...
- **Priority:** High / Medium / Low
- **Source:** Explicit / [INFERRED]
- **Acceptance Criteria:**
  1. ...
  2. ...
  3. ...

[repeat for each FR]

## 7. Non-Functional Requirements
| ID | Category | Description | Metric / Target |
|---|---|---|---|
[table rows — include Performance, Security, Availability, Scalability, Usability]

## 8. Business Rules
- **BR-01:** [Rule — use if/then where possible]
- **BR-02:** ...

## 9. Process Flow (Happy Path)
| Step | Actor | Action | Outcome |
|---|---|---|---|
[table rows describing the main end-to-end flow]

## 10. Edge Cases & Exception Handling
| ID | Scenario | Expected Behaviour |
|---|---|---|
[table rows]

## 11. Risks
| ID | Description | Likelihood | Impact | Mitigation |
|---|---|---|---|---|
[table rows]

## 12. Open Questions
| ID | Question | Status |
|---|---|---|
[table rows — flag anything unclear from the input]

---
*Document generated by FRD AI Agent — Review before client delivery.*
"""


FRD_USER_TEMPLATE = """
## PROJECT NAME: {project_name}
## TODAY'S DATE: {date}

---
{combined_input}

---
{rag_context}

---
Now generate the complete FRD following the exact format specified.
Make sure every section is present and every Functional Requirement has full acceptance criteria.
"""


class FRDGeneratorService:
    """
    Orchestrates the FRD generation using:
    1. Cleaned + combined input documents
    2. RAG context from similar past FRDs
    3. LLM call with the MASTER PROMPT
    """

    def __init__(self, llm: LLMService) -> None:
        self._llm = llm

    def generate(
        self,
        project_name: str,
        combined_input: str,
        rag_context: str,
    ) -> str:
        """
        Generate the FRD Markdown string.
        Returns the raw Markdown text.
        """
        system = SYSTEM_PROMPT.format(
            project_name=project_name,
            date=date.today().isoformat(),
        )

        user = FRD_USER_TEMPLATE.format(
            project_name=project_name,
            date=date.today().isoformat(),
            combined_input=combined_input,
            rag_context=rag_context,
        )

        print(f"[FRDGenerator] Calling LLM for project: {project_name}")
        frd_markdown = self._llm.complete(
            system_prompt=system,
            user_prompt=user,
            temperature=0.2,
            max_tokens=2048,
        )

        return frd_markdown
